#home:
#  path: /
#  defaults: { _controller: 'AppBundle\Controller\DefaultController::indexAction' }
#  methods:  GET
#

setupcheck:
  path: /api/setup-check
  controller: App\Controller\DefaultController::setupCheck

exchangerates:
  path: /api/getTable
  controller: App\Controller\ExchangeRatesController::getTable
  methods: GET

index:
  path: /{wildcard}
  defaults: { _controller: App\Controller\DefaultController::index }
  requirements:
    wildcard: .*
  # controller: App\Controller\DefaultController::index
